apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: flagfavtag
build:
  artifacts:
  - image: cxm-dev.docker.repositories.sap.ondemand.com/cxm/flagfavtag
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - K8S/node-service-demo.yaml
